# Generated by Django 5.2.15 on 2026-09-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_add_bed_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='bed_id',
            new_name='id',
        ),
    ]
