# Generated by Django 5.2.15 on 2026-07-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_payment_method_booking_rent_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=20, null=True),
        ),
    ]
