# Generated by Django 5.1.6 on 2026-07-22 07:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_payment_method'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='floor_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rent_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='requested_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_profile_photo',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='marked_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='marked_paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_marked_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='student_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='student_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bed_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
