"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlparse

from decouple import config, Csv
from django.core.exceptions import ImproperlyConfigured
import dj_database_url

logger = logging.getLogger('apps.startup')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG is off unless the environment turns it on.
DEBUG = config('DEBUG', default=False, cast=bool)

# Required environment variables that are missing. Collected so one clear
# error names all of them, then raised after the database block below.
# Only NAMES are ever reported, never values.
_missing_env = []

# SECURITY WARNING: keep the secret key used in production secret!
# Never log or print this value, not even partially masked.
# With DEBUG on, a fixed development-only key is used so tokens and sessions
# survive restarts; it is not a secret and must never be used in production.
SECRET_KEY = config('SECRET_KEY', default='')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'dev-only-insecure-key-not-for-production'
    else:
        _missing_env.append('SECRET_KEY')

if DEBUG:
    # Development: let phones and emulators on the local network connect.
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())
    if not ALLOWED_HOSTS:
        _missing_env.append('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    
    # Local apps
    'apps.core',
    'apps.owners',
    'apps.hostels',
    'apps.rooms',
    'apps.media_uploads',
    'apps.bookings',
    'apps.payments',
    'apps.dashboard',
    'apps.otp_auth',
    'apps.residents',
    'apps.notices',
]

MIDDLEWARE = [
    'apps.core.health.HealthzMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Three options, controlled by USE_DB in .env:
#   - 'supabase' (default): use DATABASE_URL (Supabase / remote Postgres)
#   - 'local':   use LOCAL_DATABASE_URL (local Postgres for development)
#   - 'sqlite':  fall back to a local SQLite file

USE_DB = config('USE_DB', default='supabase')

# Persistent connection lifetime (seconds). Was 0 (a fresh handshake per
# request); raised to reuse connections across requests within a worker.
DB_CONN_MAX_AGE = config('DB_CONN_MAX_AGE', default=60, cast=int)

if USE_DB == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    logger.info("Database configured: sqlite")
    if not DEBUG:
        logger.warning("USE_DB=sqlite with DEBUG off: data is not durable. Use a Postgres DATABASE_URL.")
elif USE_DB == 'local':
    DATABASES = {
        'default': dj_database_url.config(
            default=config('LOCAL_DATABASE_URL', default='postgresql://postgres:postgres@localhost:5432/hh_core'),
            conn_max_age=DB_CONN_MAX_AGE,
            conn_health_checks=True,
        )
    }
    logger.info("Database configured: local postgres")
else:
    _database_url = config('DATABASE_URL', default='')
    if not _database_url:
        _missing_env.append('DATABASE_URL')
    DATABASES = {
        'default': dj_database_url.config(
            default=_database_url,
            conn_max_age=DB_CONN_MAX_AGE,
            conn_health_checks=True,
        )
    }
    logger.info("Database configured: supabase")

if _missing_env:
    raise ImproperlyConfigured(
        "Missing required environment variables: " + ", ".join(_missing_env)
        + ". Set them in the process environment (see .env.example for the full list)."
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# `collectstatic` gathers admin/DRF assets here; WhiteNoise serves them.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom User Model
AUTH_USER_MODEL = 'owners.Owner'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'utils.pagination.CustomPageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        # General public/browsing traffic (hostel list/search/localities, etc.)
        'anon': '60/min',
        'user': '120/min',
        # Tighter scope for abuse-sensitive OTP send/verify endpoints.
        # Sits alongside the existing per-email cooldown in OTPService, not a replacement.
        'otp': '5/min',
    },
}

# JWT lifetimes. Rotation stays off: the shipped app does not need it.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=config('JWT_ACCESS_MINUTES', default=30, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=config('JWT_REFRESH_DAYS', default=30, cast=int)),
}

# CORS Configuration
# Browsers only: the mobile app does not use CORS. With DEBUG off, only the
# origins listed in CORS_ALLOWED_ORIGINS (comma-separated, with scheme) may call the API.
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='', cast=Csv())
    for _origin in CORS_ALLOWED_ORIGINS:
        _parts = urlparse(_origin)
        if not _parts.scheme or not _parts.netloc:
            raise ImproperlyConfigured(
                f"CORS_ALLOWED_ORIGINS entry {_origin!r} needs a scheme, e.g. https://example.com"
            )

# HTTPS / cookies. Behind a TLS-terminating proxy (Render, nginx) the proxy
# sets X-Forwarded-Proto; set TRUST_PROXY_SSL_HEADER=False if gunicorn is
# exposed directly with no such proxy.
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())
if not DEBUG and config('TRUST_PROXY_SSL_HEADER', default=True, cast=bool):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=not DEBUG, cast=bool)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# HSTS is hard to undo, so it starts off. Raise it once HTTPS is proven.
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)

# Development only: allow OTP values in responses/logs. Needs DEBUG on as well.
EXPOSE_DEV_OTP = config('EXPOSE_DEV_OTP', default=False, cast=bool)

# Email Configuration (SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_TIMEOUT = 15  # Prevent Gunicorn worker timeout if Render blocks SMTP ports
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Hostel Hunt <noreply@hostelhunt.com>')

# Twilio SMS Configuration
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_FROM_NUMBER = config('TWILIO_FROM_NUMBER', default='')

# Logging Configuration (stdout only; the host collects it)
LOG_LEVEL = config('DJANGO_LOG_LEVEL', default='INFO')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
        'apps': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': True,
        },
    },
}

# Startup Validation
if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    logger.warning("CRITICAL: EMAIL_HOST_USER and/or EMAIL_HOST_PASSWORD are not set. Email OTPs will fail.")
if not TWILIO_ACCOUNT_SID or not TWILIO_AUTH_TOKEN or not TWILIO_FROM_NUMBER:
    logger.warning("CRITICAL: Twilio configuration is missing. SMS OTPs will fail and return a 503 error.")

# ─────────────────────────────────────────────────────────────────────────────
# Razorpay Configuration
# KEY_ID is the public-facing key — safe to send to Flutter client.
# KEY_SECRET and WEBHOOK_SECRET MUST remain server-side only — never serialise
# them into any API response.
# ─────────────────────────────────────────────────────────────────────────────
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default='')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET', default='')
RAZORPAY_WEBHOOK_SECRET = config('RAZORPAY_WEBHOOK_SECRET', default='')

if not RAZORPAY_KEY_ID or not RAZORPAY_KEY_SECRET:
    logger.warning("CRITICAL: RAZORPAY_KEY_ID or RAZORPAY_KEY_SECRET is not set. Online payments will fail.")
if not RAZORPAY_WEBHOOK_SECRET:
    logger.warning("CRITICAL: RAZORPAY_WEBHOOK_SECRET is not set. Webhook verification will fail.")
