# Generated by Django 5.2.15 on 2026-06-18 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.UUIDField(db_column='hostel_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_maps_url', models.URLField(blank=True, max_length=500, null=True)),
                ('gender_type', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('co_living', 'Co-Living')], max_length=20)),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('occupancy_types', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, null=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('check_in_policy', models.CharField(blank=True, max_length=255, null=True)),
                ('check_out_policy', models.CharField(blank=True, max_length=255, null=True)),
                ('amenities', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hostels',
                'ordering': ['-created_at'],
            },
        ),
    ]
