# Generated by Django 5.2.15 on 2026-07-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='locality',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
