# Generated by Django 5.1.6 on 2026-07-22 07:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0006_alter_booking_options_remove_booking_check_in_date_and_more'),
        ('hostels', '0002_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.UUIDField(db_column='resident_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('id_proof_type', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('other', 'Other')], max_length=20)),
                ('id_proof_number', models.CharField(max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('move_in_date', models.DateField()),
                ('expected_move_out_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('vacated', 'Vacated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='hostels.hostel')),
                ('linked_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_residents', to='bookings.booking')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='rooms.room')),
            ],
            options={
                'db_table': 'residents',
                'ordering': ['-created_at'],
            },
        ),
    ]
