# Generated by Django 5.2.15 on 2026-06-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprecord',
            name='verification_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
