# Generated by Django 5.2.15 on 2026-07-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_otprecord_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprecord',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
