# Generated by Django 5.2.15 on 2026-07-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_otprecord_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='signup_source',
            field=models.CharField(blank=True, default='admin_panel', max_length=50),
        ),
    ]
