from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated, AllowAny
from django.utils import timezone
from .models import Booking
from .serializers import BookingSerializer, BookingCreateSerializer
from apps.core.querysets import TenantScopedQuerysetMixin
from apps.core.utils import get_tenant_scoped_object_or_404


class BookingViewSet(TenantScopedQuerysetMixin, viewsets.ModelViewSet):
    """
    Router-registered ViewSet for Booking.

    Standard routes (auto-generated by Router):
        GET    /bookings/          — list bookings for the authenticated owner
        POST   /bookings/          — create a new booking (public, from Flutter app)
        GET    /bookings/<pk>/     — retrieve a single booking
        PUT    /bookings/<pk>/     — (disabled via http_method_names)
        PATCH  /bookings/<pk>/     — (disabled via http_method_names)
        DELETE /bookings/<pk>/     — (disabled via http_method_names)

    Custom actions:
        POST  /bookings/<pk>/approve/   — confirm an offline booking
        POST  /bookings/<pk>/reject/    — reject a booking
        POST  /bookings/<pk>/verify/    — verify online payment and confirm booking
        PATCH /bookings/<pk>/mark_paid/ — mark an offline booking as paid

    Query params (list):
        payment_mode=offline|online
        status=pending|confirmed|paid|cancelled|rejected
    """

    queryset = Booking.objects.select_related('hostel', 'room')
    # Disable direct edit/delete through the standard REST verbs;
    # all state changes go through the explicit custom actions.
    http_method_names = ['get', 'post', 'patch', 'head', 'options']

    def get_serializer_class(self):
        if self.action == 'create':
            return BookingCreateSerializer
        return BookingSerializer

    def get_permissions(self):
        if self.action == 'create':
            return [AllowAny()]
        return [IsAuthenticated()]

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Booking.objects.none()

        # TenantScopedQuerysetMixin handles hostel__owner scoping via OWNER_LOOKUP.
        qs = super().get_queryset()
        payment_mode = self.request.query_params.get('payment_mode')
        if payment_mode:
            qs = qs.filter(payment_mode=payment_mode)
        booking_status = self.request.query_params.get('status')
        if booking_status:
            qs = qs.filter(status=booking_status)
        return qs

    # ------------------------------------------------------------------ #
    #  Custom actions                                                       #
    # ------------------------------------------------------------------ #

    @action(detail=True, methods=['post'], permission_classes=[IsAuthenticated])
    def approve(self, request, pk=None):
        """POST /bookings/<pk>/approve/ — confirm an offline booking."""
        booking = get_tenant_scoped_object_or_404(Booking, pk, request)

        if booking.status != 'pending':
            return Response(
                {"error": "Only pending bookings can be confirmed"},
                status=status.HTTP_400_BAD_REQUEST,
            )

        booking.status = 'confirmed'
        booking.save(update_fields=['status', 'updated_at'])
        return Response({"success": True, "data": BookingSerializer(booking).data})

    @action(detail=True, methods=['post'], permission_classes=[IsAuthenticated])
    def reject(self, request, pk=None):
        """POST /bookings/<pk>/reject/ — reject a booking."""
        booking = get_tenant_scoped_object_or_404(Booking, pk, request)

        if booking.status not in ('pending', 'confirmed'):
            return Response(
                {"error": "Cannot reject a booking that is already paid or cancelled"},
                status=status.HTTP_400_BAD_REQUEST,
            )

        booking.status = 'rejected'
        booking.save(update_fields=['status', 'updated_at'])
        return Response({"success": True, "data": BookingSerializer(booking).data})

    @action(detail=True, methods=['post'], permission_classes=[IsAuthenticated])
    def verify(self, request, pk=None):
        """POST /bookings/<pk>/verify/ — verify an online payment and confirm booking."""
        booking = get_tenant_scoped_object_or_404(Booking, pk, request)

        if booking.payment_mode != 'online':
            return Response(
                {"error": "Only online bookings can be verified"},
                status=status.HTTP_400_BAD_REQUEST,
            )

        booking.status = 'paid'
        booking.marked_paid_by = request.user
        booking.marked_paid_at = timezone.now()
        booking.save(update_fields=['status', 'marked_paid_by', 'marked_paid_at', 'updated_at'])
        return Response({"success": True, "data": BookingSerializer(booking).data})

    @action(detail=True, methods=['patch'], permission_classes=[IsAuthenticated], url_path='mark-paid')
    def mark_paid(self, request, pk=None):
        """PATCH /bookings/<pk>/mark-paid/ — mark an offline booking as paid."""
        booking = get_tenant_scoped_object_or_404(Booking, pk, request)

        if booking.status not in ('pending', 'confirmed'):
            return Response(
                {"error": "Can only mark pending or confirmed bookings as paid"},
                status=status.HTTP_400_BAD_REQUEST,
            )

        booking.status = 'paid'
        booking.marked_paid_by = request.user
        booking.marked_paid_at = timezone.now()
        booking.save(update_fields=['status', 'marked_paid_by', 'marked_paid_at', 'updated_at'])
        return Response({"success": True, "data": BookingSerializer(booking).data})
