# Generated by Django 5.2.15 on 2026-07-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0004_owner_signup_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRecord',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('owners.otprecord',),
        ),
    ]
