# Generated by Django 5.2.15 on 2026-09-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_replace_payment_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='id',
        ),
    ]
