# Generated by Django 5.2.15 on 2026-07-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='file',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='file_url',
            field=models.URLField(default='http://example.com/default.jpg', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
